Controllers/ProfilController.cs
using asp_net_parcijalni_ispit_Ivan_Blazun.Data;
using asp_net_parcijalni_ispit_Ivan_Blazun.Models;
using asp_net_parcijalni_ispit_Ivan_Blazun.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace asp_net_parcijalni_ispit_Ivan_Blazun.Controllers
{
	[Authorize]

	public class ProfilController : Controller
	{
		private readonly UserManager<AspNetUser> _userManager;
		private readonly ApplicationDbContext _context;

		public ProfilController(UserManager<AspNetUser> userManager, ApplicationDbContext context)
		{
			_userManager = userManager;
			_context = context;
		}
		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var model = new UpdateViewModel();
			var user = await _userManager.GetUserAsync(User);
			var tasks = await _context.TaskItems.Where(t => t.UserId == user.Id).ToListAsync();

			model.Ime = user.FirstName;
			model.Prezime = user.LastName;
			model.Adresa = user.Address;
			model.TaskItems = tasks;
			return View(model);
		}
		[HttpPost]
		public async Task<IActionResult> UpdateData(UpdateViewModel model)
		{
			
				var user = await _userManager.GetUserAsync(User);
				user.FirstName = model.Ime;
				user.LastName= model.Prezime;
				user.Address = model.Adresa;
				var result = await _userManager.UpdateAsync(user);
				if (result.Succeeded)
				{
					return View("UpgradeData");
				}
			
			return View("Error");
		}
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - AspIspit</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspIspit</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Profil" asp-action="Index">Profil</a>
						</li>
@*						<partial name="_AdminMenuPartial" />*@
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
					</ul>
					<partial name="_LoginPartial" />
					<partial name="_MenuPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			!copy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<AspNetUser> SignInManager


@if (SignInManager.IsSignedIn(User))
{
	<li class="nav-item">
		<div class="dropdown">
			<a class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" href="#">
				Vaši zadaci
			</a>
			<div class="dropdown-menu">
				<a class="dropdown-item" asp-controller="TaskItems" asp-action="Index">Lista zadataka</a>
				<a class="dropdown-item" asp-controller="TaskItems" asp-action="Create">Novi zadatak</a>
			</div>
		</div>
	</li>
}